# Generated by Django 4.1.3 on 2022-12-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
