# Generated by Django 4.1.3 on 2022-12-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dispprior',
            field=models.IntegerField(),
        ),
    ]
