# Generated by Django 4.1.3 on 2022-12-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_dispprior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['dispprior']},
        ),
    ]
