# Generated by Django 4.1.3 on 2022-11-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_room_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(auto_now_add=True)),
                ('check_out', models.DateField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=225)),
                ('customer_address', models.CharField(max_length=225)),
                ('room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rooms.room')),
            ],
        ),
    ]
