# Generated by Django 4.1.3 on 2022-12-05 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_customer_number_reservation_no_of_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room',
            new_name='roomNumber',
        ),
        migrations.AddField(
            model_name='reservation',
            name='book_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
