# Generated by Django 4.1.3 on 2022-12-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_room_reservation_roomnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Discount',
            field=models.CharField(blank=True, choices=[(None, 'No Discount'), ('10', '10%'), ('20', '20%'), ('30', '30%'), ('Oth', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Pay_Type',
            field=models.CharField(blank=True, choices=[('P', 'Paying'), ('PD', 'Paying Debtor'), ('NP', 'Non Paying')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
