# Generated by Django 4.1.3 on 2022-12-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_discount_reservation_pay_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Discount',
            new_name='discount',
        ),
    ]
