# Generated by Django 4.1.3 on 2022-12-09 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_rename_discount_reservation_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(default=datetime.datetime(2022, 12, 9, 7, 12, 13, 702165, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(default=datetime.datetime(2022, 12, 9, 7, 12, 28, 960920, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
