# Generated by Django 4.1.3 on 2022-12-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_reservation_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='roomstatus',
            field=models.CharField(blank=True, choices=[('reserve', 'reserve'), ('checkin', 'checkin'), ('checkout', 'checkout')], default='reserve', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='discount',
            field=models.CharField(blank=True, choices=[('reserve', 'reserve'), ('checkin', 'checkin'), ('checkout', 'checkout')], default='20', max_length=20, null=True),
        ),
    ]
