# Generated by Django 4.1.3 on 2022-12-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_alter_reservation_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='any_field',
        ),
        migrations.AddField(
            model_name='reservation',
            name='checking_in_now',
            field=models.BooleanField(default=True),
        ),
    ]
