# Generated by Django 4.1.3 on 2022-12-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_remove_reservation_any_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='checking_in_now',
        ),
    ]
