# Generated by Django 4.1.3 on 2022-12-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_remove_reservation_checking_in_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checking_in_now',
            field=models.BooleanField(default=False),
        ),
    ]
