# Generated by Django 4.1.3 on 2022-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_reservation_checking_in_now'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Pay_Type',
            new_name='payment_type',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('C', 'Cash'), ('P', 'POS'), ('TF', 'Transfer')], max_length=20, null=True),
        ),
    ]
