# Generated by Django 4.1.3 on 2022-12-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_reservation_credit_balance_reservation_paid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='paid_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
