# Generated by Django 4.1.3 on 2022-12-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_alter_reservation_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='extra_field',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
